# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=25)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
    ]
